# shellcheck shell=bash
# Shared helpers for bootstrap / unbootstrap path tracking.
# Manifest: .ai/framework-manifest (one repo-relative path per line)

FM_VERSION=1
FM_FILE=".ai/framework-manifest"

fm_target_root() {
  local t="${1:-.}"
  (cd "$t" && pwd)
}

fm_manifest_path() {
  local root="$1"
  echo "$root/$FM_FILE"
}

fm_ensure_dir() {
  local root="$1"
  mkdir -p "$root/.ai"
}

fm_init() {
  local root="$1"
  fm_ensure_dir "$root"
  local mf
  mf="$(fm_manifest_path "$root")"
  if [ ! -f "$mf" ]; then
    cat > "$mf" <<EOF
# terminal-ai-workflow manifest v${FM_VERSION}
# Generated by bootstrap scripts. Used by unbootstrap-project.
EOF
  fi
}

fm_add() {
  local root="$1" rel="$2"
  [ -n "$rel" ] || return 0
  fm_init "$root"
  local mf
  mf="$(fm_manifest_path "$root")"
  if grep -Fxq "$rel" "$mf" 2>/dev/null; then
    return 0
  fi
  echo "$rel" >> "$mf"
}

fm_add_dir() {
  local root="$1" rel="$2"
  rel="${rel%/}/"
  fm_add "$root" "$rel"
}

fm_list_paths() {
  local root="$1"
  local mf
  mf="$(fm_manifest_path "$root")"
  if [ -f "$mf" ]; then
    grep -v '^#' "$mf" | grep -v '^[[:space:]]*$' || true
  fi
}

fm_strip_gitignore_block() {
  local gitignore="$1"
  [ -f "$gitignore" ] || return 0
  python3 - "$gitignore" <<'PY'
import sys
path = sys.argv[1]
with open(path) as f:
    lines = f.readlines()
out = []
skip = False
for line in lines:
    if line.strip() == "# >>> ai-framework-ignore":
        skip = True
        continue
    if line.strip() == "# <<< ai-framework-ignore":
        skip = False
        continue
    if not skip:
        out.append(line)
while out and out[-1].strip() == "":
    out.pop()
text = "".join(out)
if text and not text.endswith("\n"):
    text += "\n"
with open(path, "w") as f:
    f.write(text)
PY
}
